#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/openpgpkey-milter" ]; then
	if [ ! -e "/etc/init/openpgpkey-milter.conf" ]; then
		update-rc.d openpgpkey-milter defaults >/dev/null
	fi
	invoke-rc.d openpgpkey-milter start || exit $?
fi
# End automatically added section
