Document: openpgpkey-milter
Title: Debian openpgpkey-milter Manual
Author: <insert document author here>
Abstract: This manual describes what openpgpkey-milter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openpgpkey-milter/openpgpkey-milter.sgml.gz

Format: postscript
Files: /usr/share/doc/openpgpkey-milter/openpgpkey-milter.ps.gz

Format: text
Files: /usr/share/doc/openpgpkey-milter/openpgpkey-milter.text.gz

Format: HTML
Index: /usr/share/doc/openpgpkey-milter/html/index.html
Files: /usr/share/doc/openpgpkey-milter/html/*.html
